# Generated by Django 4.0.4 on 2022-05-11 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDireccion', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('comuna', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('depto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serieCliente', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=30)),
                ('id_usuario', models.CharField(max_length=10)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.direccion')),
            ],
        ),
    ]
